repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: autoformat
        entry: .pre-commit-hooks/rustfmt.sh
        language: script
        files: \.rs$

      - id: clippy
        name: clippy_linter
        entry: .pre-commit-hooks/clippy.sh
        language: script
        files: \.rs$

      - id: audit
        name: dependency_audit
        entry: .pre-commit-hooks/audit.sh
        language: script
        pass_filenames: false
